<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Report extends Model
{
    protected $table = 'reports';
    protected $primaryKey = 'ReportID';
    public $incrementing = true;
    protected $keyType = 'int';
    public $timestamps = true;

    protected $fillable = [
        'Content',
        'CreatedDate',
        'UserID',
        'ApplicationID',
    ];

    protected $casts = [
        'CreatedDate' => 'date',
    ];

    /* =========================
     | RELATIONSHIPS
     ========================= */

    /**
     * Report generated by admin
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class, 'UserID', 'UserID');
    }

    /**
     * Related application (optional context)
     */
    public function application(): BelongsTo
    {
        return $this->belongsTo(Application::class, 'ApplicationID', 'ApplicationID');
    }
}
